#pragma once

namespace Biribit
{
	enum ErrorType
	{
		ERROR_CODE = 0,
		WARN_CLIENT_NAME_IN_USE,
		WARN_CANNOT_LIST_ROOMS_WITHOUT_APPID,
		WARN_CANNOT_CREATE_ROOM_WITHOUT_APPID,
		WARN_CANNOT_CREATE_ROOM_WITH_WRONG_SLOT_NUMBER,
		WARN_CANNOT_CREATE_ROOM_WITH_TOO_MANY_SLOTS,
		WARN_CANNOT_JOIN_WITHOUT_ROOM_ID,
		WARN_CANNOT_JOIN_TO_UNEXISTING_ROOM,
		WARN_CANNOT_JOIN_TO_OTHER_APP_ROOM,
		WARN_CANNOT_JOIN_TO_OCCUPIED_SLOT,
		WARN_CANNOT_JOIN_TO_INVALID_SLOT,
		WARN_CANNOT_JOIN_TO_FULL_ROOM
	};
}